[package]
name = "rust-mcp-remote"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.23.1"
httpdate = "1.0.3"
libc = "0.2.190"
md5 = "0.8.1"
reqwest = { version = "0.13.5", features = ["json", "stream"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
sha2 = "0.11.0"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "io-util", "io-std", "sync", "time", "net", "signal", "process"] }
url = "2.5.8"
uuid = { version = "1.27.0", features = ["v4"] }
